version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    hostname: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env.production
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  app:
    container_name: task-backend
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env.production
volumes:
  mongo-data:
